
import React, { useState } from 'react';
import { Product } from '../../types';
import { Plus, Edit2, Trash2, Search, AlertCircle, Package, X, Percent, Lock, Settings2 } from 'lucide-react';
import { formatCurrency } from '../../services/currencyUtils';

interface InventoryManagementProps {
  products: Product[];
  onAdd: (product: Product) => Promise<void>;
  onEdit: (product: Product) => Promise<void>;
  onDelete: (productId: string) => Promise<void>;
  isAdmin: boolean;
  currency: any;
  isSubscribed: boolean;
  categories: string[];
  onUpdateCategories: (categories: string[]) => void;
}

const InventoryManagement: React.FC<InventoryManagementProps> = ({
  products,
  onAdd,
  onEdit,
  onDelete,
  isAdmin,
  currency,
  isSubscribed,
  categories,
  onUpdateCategories
}) => {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [isCategoryModalOpen, setIsCategoryModalOpen] = useState(false);
  const [editingProduct, setEditingProduct] = useState<Product | null>(null);
  const [filter, setFilter] = useState('');
  const [newCategoryName, setNewCategoryName] = useState('');

  const handleDelete = async (id: string) => {
    if (confirm("Permanently remove this product from inventory?")) {
      await onDelete(id);
    }
  };

  const handleSave = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const formData = new FormData(e.currentTarget);
    const newProduct: Product = {
      id: editingProduct?.id || '', // ID will be generated by DB if empty/new
      name: formData.get('name') as string,
      sku: formData.get('sku') as string,
      category: formData.get('category') as string,
      buyPrice: Number(formData.get('buyPrice')),
      sellPrice: Number(formData.get('sellPrice')),
      quantity: Number(formData.get('quantity')),
      minThreshold: Number(formData.get('minThreshold')),
      discount: Number(formData.get('discount')) || 0,
    };

    if (editingProduct) {
      await onEdit(newProduct);
    } else {
      await onAdd(newProduct);
    }
    setIsModalOpen(false);
    setEditingProduct(null);
  };

  const handleAddCategory = () => {
    if (!newCategoryName.trim()) return;
    if (categories.includes(newCategoryName.trim())) {
      alert("This category already exists.");
      return;
    }
    onUpdateCategories([...categories, newCategoryName.trim()]);
    setNewCategoryName('');
  };

  const handleDeleteCategory = (cat: string) => {
    const hasProducts = products.some(p => p.category === cat);
    if (hasProducts) {
      if (!confirm(`Warning: There are products currently assigned to "${cat}". Are you sure you want to delete this category?`)) {
        return;
      }
    } else {
      if (!confirm(`Are you sure you want to delete the "${cat}" category?`)) return;
    }
    onUpdateCategories(categories.filter(c => c !== cat));
  };

  const filtered = products.filter(p =>
    p.name.toLowerCase().includes(filter.toLowerCase()) ||
    p.sku.toLowerCase().includes(filter.toLowerCase())
  );

  const formatPrice = (val: number) => {
    return formatCurrency(val, currency);
  };

  return (
    <div className="bg-white rounded-3xl shadow-sm border border-slate-100 overflow-hidden">
      <div className="p-6 border-b border-slate-50 flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div className="relative max-w-sm w-full">
          <span className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400">
            <Search size={18} />
          </span>
          <input
            type="text"
            placeholder="Search SKU or Name..."
            value={filter}
            onChange={(e) => setFilter(e.target.value)}
            className="w-full pl-11 pr-4 py-3 bg-slate-50 border border-slate-100 rounded-2xl text-sm focus:outline-none focus:ring-4 focus:ring-blue-100 focus:bg-white transition-all"
          />
        </div>

        <div className="flex items-center gap-3">
          {isAdmin && (
            <button
              onClick={() => setIsCategoryModalOpen(true)}
              className="flex items-center gap-2 bg-slate-100 hover:bg-slate-200 text-slate-700 px-5 py-3 rounded-2xl text-sm font-bold transition-all active:scale-95"
            >
              <Settings2 size={18} /> Manage Categories
            </button>
          )}

          {isAdmin && (
            isSubscribed ? (
              <button
                onClick={() => {
                  setEditingProduct(null);
                  setIsModalOpen(true);
                }}
                className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white px-5 py-3 rounded-2xl text-sm font-bold shadow-lg shadow-blue-100 transition-all active:scale-95"
              >
                <Plus size={18} /> New Product
              </button>
            ) : (
              <div className="flex items-center gap-3 px-5 py-3 bg-slate-100 rounded-2xl text-slate-400 border border-slate-200">
                <Lock size={16} />
                <span className="text-xs font-bold uppercase tracking-widest">Upgrade to Add Stock</span>
              </div>
            )
          )}
        </div>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full text-left">
          <thead>
            <tr className="bg-slate-50/50 text-slate-400 text-[10px] font-bold uppercase tracking-[0.2em]">
              <th className="px-8 py-5">Inventory Item</th>
              <th className="px-8 py-5">Category</th>
              <th className="px-8 py-5">Stock Health</th>
              <th className="px-8 py-5">Initial Stock</th>
              <th className="px-8 py-5">Unit Price</th>
              <th className="px-8 py-5">Total Value</th>
              <th className="px-8 py-5">Discount</th>
              {isAdmin && <th className="px-8 py-5">Operations</th>}
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-50">
            {filtered.map(product => {
              const isLow = product.quantity <= product.minThreshold;
              const isOut = product.quantity <= 0;
              const hasDiscount = (product.discount || 0) > 0;

              return (
                <tr key={product.id} className="hover:bg-slate-50/30 transition-colors group">
                  <td className="px-8 py-5">
                    <div className="flex items-center gap-4">
                      <div className={`p-3 rounded-2xl ${isOut ? 'bg-slate-100 text-slate-400' : isLow ? 'bg-red-50 text-red-500' : 'bg-blue-50 text-blue-600'}`}>
                        <Package size={20} />
                      </div>
                      <div>
                        <div className="font-bold text-slate-800 text-base">{product.name}</div>
                        <div className="text-xs text-slate-400 font-mono">#{product.sku}</div>
                      </div>
                    </div>
                  </td>
                  <td className="px-8 py-5">
                    <span className="px-3 py-1.5 bg-slate-100 text-slate-500 rounded-xl text-[10px] font-bold uppercase tracking-wider">
                      {product.category}
                    </span>
                  </td>
                  <td className="px-8 py-5">
                    <div className="space-y-1.5">
                      <div className="flex items-center gap-2">
                        <span className={`text-sm font-black ${isOut ? 'text-slate-400' : isLow ? 'text-red-500' : 'text-slate-700'}`}>
                          {product.quantity} units
                        </span>
                        {isLow && (
                          <div className="text-red-500 animate-bounce">
                            <AlertCircle size={14} strokeWidth={3} />
                          </div>
                        )}
                      </div>
                      <div className="w-32 h-1.5 bg-slate-100 rounded-full overflow-hidden">
                        <div
                          className={`h-full transition-all duration-500 ${isOut ? 'w-0' : isLow ? 'bg-red-500 w-1/4' : 'bg-emerald-500 w-full'}`}
                        ></div>
                      </div>
                    </div>
                  </td>
                  <td className="px-8 py-5">
                    <div className="text-sm font-bold text-slate-600">
                      {product.initialQuantity !== undefined ? product.initialQuantity : '-'} units
                    </div>
                  </td>
                  <td className="px-8 py-5">
                    <div className="text-sm font-bold text-slate-800">{formatPrice(product.sellPrice)}</div>
                    {isAdmin && <div className="text-[10px] text-slate-400 font-bold uppercase">Cost: {formatPrice(product.buyPrice)}</div>}
                  </td>
                  <td className="px-8 py-5">
                    <div className="text-sm font-black text-emerald-600">
                      {formatPrice(product.sellPrice * product.quantity)}
                    </div>
                  </td>
                  <td className="px-8 py-5">
                    {hasDiscount ? (
                      <div className="flex items-center gap-1.5 bg-orange-50 text-orange-600 px-2.5 py-1 rounded-lg w-fit">
                        <Percent size={12} strokeWidth={3} />
                        <span className="text-xs font-black">{product.discount}% OFF</span>
                      </div>
                    ) : (
                      <span className="text-slate-300 text-xs">-</span>
                    )}
                  </td>
                  {isAdmin && (
                    <td className="px-8 py-5">
                      <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                        <button
                          onClick={() => {
                            if (!isSubscribed) return alert("Upgrade to Basic to edit products.");
                            setEditingProduct(product);
                            setIsModalOpen(true);
                          }}
                          className={`p-2.5 rounded-xl transition-all ${isSubscribed ? 'text-slate-400 hover:text-blue-600 hover:bg-blue-50' : 'text-slate-200 cursor-not-allowed'}`}
                        >
                          {isSubscribed ? <Edit2 size={16} /> : <Lock size={16} />}
                        </button>
                        <button
                          onClick={() => {
                            if (!isSubscribed) return alert("Upgrade to Basic to delete products.");
                            handleDelete(product.id);
                          }}
                          className={`p-2.5 rounded-xl transition-all ${isSubscribed ? 'text-slate-400 hover:text-red-600 hover:bg-red-50' : 'text-slate-200 cursor-not-allowed'}`}
                        >
                          {isSubscribed ? <Trash2 size={16} /> : <Lock size={16} />}
                        </button>
                      </div>
                    </td>
                  )}
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      {/* Grand Total Footer */}
      <div className="bg-slate-50 border-t border-slate-100 p-6 flex flex-col md:flex-row justify-between items-center gap-4">
        <div className="text-slate-500 text-sm font-medium">
          Total Products: <span className="font-bold text-slate-800">{products.length}</span>
        </div>
        <div className="flex items-center gap-3">
          <span className="text-sm font-bold text-slate-500 uppercase tracking-wider">Estimated Grand Total Value:</span>
          <span className="text-2xl font-black text-slate-800">
            {formatPrice(products.reduce((sum, p) => sum + (p.sellPrice * p.quantity), 0))}
          </span>
        </div>
      </div>

      {/* Category Management Modal */}
      {isCategoryModalOpen && (
        <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-sm flex items-center justify-center p-4 z-50">
          <div className="bg-white rounded-3xl w-full max-w-md shadow-2xl overflow-hidden animate-in fade-in zoom-in-95 duration-200">
            <div className="p-8 border-b border-slate-100 flex justify-between items-center bg-slate-50/50">
              <h3 className="text-xl font-bold text-slate-800 tracking-tight">Product Categories</h3>
              <button onClick={() => setIsCategoryModalOpen(false)} className="p-2 hover:bg-white rounded-full transition-colors text-slate-400">
                <X size={20} />
              </button>
            </div>
            <div className="p-8 space-y-6">
              <div className="space-y-2">
                <label className="text-xs font-black text-slate-500 uppercase tracking-widest ml-1">Add New Category</label>
                <div className="flex gap-2">
                  <input
                    type="text"
                    value={newCategoryName}
                    onChange={(e) => setNewCategoryName(e.target.value)}
                    className="flex-1 px-4 py-3 border border-slate-200 rounded-xl focus:ring-4 focus:ring-blue-100 outline-none transition-all"
                    placeholder="e.g. Stationary"
                  />
                  <button
                    onClick={handleAddCategory}
                    className="bg-blue-600 text-white p-3 rounded-xl hover:bg-blue-700 transition-all active:scale-95"
                  >
                    <Plus size={20} />
                  </button>
                </div>
              </div>

              <div className="space-y-3">
                <label className="text-xs font-black text-slate-500 uppercase tracking-widest ml-1">Current Categories</label>
                <div className="max-h-60 overflow-y-auto pr-2 space-y-2">
                  {categories.map((cat) => (
                    <div key={cat} className="flex items-center justify-between p-3 bg-slate-50 border border-slate-100 rounded-xl group hover:border-blue-200 transition-all">
                      <span className="font-semibold text-slate-700">{cat}</span>
                      <button
                        onClick={() => handleDeleteCategory(cat)}
                        className="p-1.5 text-slate-300 hover:text-red-500 transition-colors"
                      >
                        <Trash2 size={16} />
                      </button>
                    </div>
                  ))}
                </div>
              </div>

              <div className="pt-4">
                <button
                  onClick={() => setIsCategoryModalOpen(false)}
                  className="w-full py-4 bg-slate-900 text-white rounded-2xl font-bold hover:bg-slate-800 transition-all"
                >
                  Close Manager
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Product Modal */}
      {isModalOpen && (
        <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-sm flex items-center justify-center p-4 z-50">
          <div className="bg-white rounded-3xl w-full max-w-xl shadow-2xl overflow-hidden animate-in fade-in zoom-in-95 duration-200">
            <div className="p-8 border-b border-slate-50 flex justify-between items-center bg-slate-50/50">
              <div>
                <h3 className="text-xl font-bold text-slate-800">
                  {editingProduct ? 'Update Inventory' : 'Add New Item'}
                </h3>
                <p className="text-xs text-slate-500 font-medium">Record precise product metadata</p>
              </div>
              <button onClick={() => setIsModalOpen(false)} className="p-2.5 hover:bg-white hover:shadow-sm rounded-xl transition-all text-slate-400">
                <X size={20} />
              </button>
            </div>
            <form onSubmit={handleSave} className="p-8 space-y-5">
              <div className="grid grid-cols-2 gap-5">
                <div className="space-y-1.5">
                  <label className="text-xs font-bold text-slate-500 uppercase tracking-widest ml-1">Label</label>
                  <input name="name" defaultValue={editingProduct?.name} required className="w-full px-4 py-3 border border-slate-200 rounded-xl focus:ring-4 focus:ring-blue-100 outline-none transition-all" />
                </div>
                <div className="space-y-1.5">
                  <label className="text-xs font-bold text-slate-500 uppercase tracking-widest ml-1">SKU</label>
                  <input name="sku" defaultValue={editingProduct?.sku} required className="w-full px-4 py-3 border border-slate-200 rounded-xl focus:ring-4 focus:ring-blue-100 outline-none transition-all" />
                </div>
              </div>
              <div className="space-y-1.5">
                <label className="text-xs font-bold text-slate-500 uppercase tracking-widest ml-1">Category</label>
                <select name="category" defaultValue={editingProduct?.category} className="w-full px-4 py-3 border border-slate-200 rounded-xl focus:ring-4 focus:ring-blue-100 outline-none transition-all bg-white">
                  {categories.map(c => <option key={c} value={c}>{c}</option>)}
                </select>
              </div>
              <div className="grid grid-cols-3 gap-5">
                <div className="space-y-1.5">
                  <label className="text-xs font-bold text-slate-500 uppercase tracking-widest ml-1">Cost Price</label>
                  <input type="number" step="any" name="buyPrice" defaultValue={editingProduct?.buyPrice} required className="w-full px-4 py-3 border border-slate-200 rounded-xl focus:ring-4 focus:ring-blue-100 outline-none transition-all" />
                </div>
                <div className="space-y-1.5">
                  <label className="text-xs font-bold text-slate-500 uppercase tracking-widest ml-1">Sale Price</label>
                  <input type="number" step="any" name="sellPrice" defaultValue={editingProduct?.sellPrice} required className="w-full px-4 py-3 border border-slate-200 rounded-xl focus:ring-4 focus:ring-blue-100 outline-none transition-all" />
                </div>
                <div className="space-y-1.5">
                  <label className="text-xs font-bold text-slate-500 uppercase tracking-widest ml-1 text-orange-600">Discount %</label>
                  <input type="number" min="0" max="100" name="discount" defaultValue={editingProduct?.discount} className="w-full px-4 py-3 border border-orange-200 rounded-xl focus:ring-4 focus:ring-orange-100 outline-none transition-all" />
                </div>
              </div>
              <div className="grid grid-cols-2 gap-5">
                <div className="space-y-1.5">
                  <label className="text-xs font-bold text-slate-500 uppercase tracking-widest ml-1">Stock Level</label>
                  <input type="number" name="quantity" defaultValue={editingProduct?.quantity} required className="w-full px-4 py-3 border border-slate-200 rounded-xl focus:ring-4 focus:ring-blue-100 outline-none transition-all" />
                </div>
                <div className="space-y-1.5">
                  <label className="text-xs font-bold text-slate-500 uppercase tracking-widest ml-1">Min. Threshold</label>
                  <input type="number" name="minThreshold" defaultValue={editingProduct?.minThreshold} required className="w-full px-4 py-3 border border-slate-200 rounded-xl focus:ring-4 focus:ring-blue-100 outline-none transition-all" />
                </div>
              </div>
              <div className="pt-6 flex gap-4">
                <button type="button" onClick={() => setIsModalOpen(false)} className="flex-1 py-4 border-2 border-slate-100 rounded-2xl hover:bg-slate-50 transition-all font-bold text-slate-500">Cancel</button>
                <button type="submit" className="flex-1 py-4 bg-blue-600 text-white rounded-2xl hover:bg-blue-700 transition-all font-bold shadow-lg shadow-blue-100">Save Asset</button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};

export default InventoryManagement;
