
import React, { useState, useMemo } from 'react';
import { Sale, Product, DailyRecord } from '../../types';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import {
    FileText, TrendingUp, TrendingDown, DollarSign, Calendar, Save, Printer,
    ArrowUpCircle, ArrowDownCircle
} from 'lucide-react';
import Reports from './Reports';

interface TransactionPageProps {
    sales: Sale[];
    products: Product[];
    dailyRecords: DailyRecord[];
    onUpdateRecord: (record: DailyRecord) => Promise<void>;
    currency: any;
    isPremium: boolean;
    isAdmin: boolean;
    initialCapital: number;
    onUpdateInitialCapital: (amount: number) => Promise<void>;
    expenses?: any[];
}

const TransactionPage: React.FC<TransactionPageProps> = ({
    sales, products, dailyRecords, onUpdateRecord, currency, isPremium, isAdmin,
    initialCapital, onUpdateInitialCapital, expenses = []
}) => {
    const [selectedDate, setSelectedDate] = useState(new Date().toISOString().split('T')[0]);
    const [openingBalance, setOpeningBalance] = useState('');
    const [stockPurchases, setStockPurchases] = useState('');
    const [otherExpenses, setOtherExpenses] = useState('');
    const [capitalInput, setCapitalInput] = useState('');
    const [isSaving, setIsSaving] = useState(false);

    // Financial calculations
    const dailyStats = useMemo(() => {
        const currentRecord = dailyRecords.find(r => r.date === selectedDate) || {
            opening_balance: 0,
            stock_purchases: 0,
            other_expenses: 0
        };

        const daySales = sales.filter(s => s.timestamp.startsWith(selectedDate));
        const totalSalesRevenue = daySales.reduce((sum, s) => sum + s.totalPrice, 0);

        // Impact Analysis
        const salesImpact = totalSalesRevenue; // Positive impact (money in)
        const purchaseImpact = currentRecord.stock_purchases; // Negative impact (money out for stock)

        const netProfit = totalSalesRevenue - (daySales.reduce((sum, s) => sum + (s.totalCost || 0), 0)) - currentRecord.other_expenses;
        const closingBalance = currentRecord.opening_balance + totalSalesRevenue - currentRecord.stock_purchases - currentRecord.other_expenses;

        // ROI Calculation based on current value vs initial check
        const capitalGrowth = initialCapital > 0 ? ((closingBalance - initialCapital) / initialCapital) * 100 : 0;
        const growthAmount = closingBalance - initialCapital;

        return {
            salesRevenue: totalSalesRevenue,
            salesImpact,
            purchaseImpact,
            netProfit,
            closingBalance,
            record: currentRecord,
            transactionCount: daySales.length,
            capitalGrowth,
            growthAmount
        };
    }, [sales, dailyRecords, selectedDate, initialCapital]);

    const handleSave = async () => {
        setIsSaving(true);
        try {
            await onUpdateRecord({
                id: dailyStats.record.id,
                date: selectedDate,
                opening_balance: Number(openingBalance) || dailyStats.record.opening_balance,
                stock_purchases: Number(stockPurchases) || dailyStats.record.stock_purchases,
                other_expenses: Number(otherExpenses) || dailyStats.record.other_expenses
            } as DailyRecord);

            if (capitalInput) {
                await onUpdateInitialCapital(Number(capitalInput));
            }

            alert('Records updated successfully!');
        } catch (err) {
            console.error(err);
        } finally {
            setIsSaving(false);
        }
    };

    const generatePDF = () => {
        const doc = new jsPDF();

        // Header
        doc.setFontSize(22);
        doc.text('Daily Transaction Report', 14, 20);

        doc.setFontSize(12);
        doc.text(`Date: ${selectedDate}`, 14, 30);
        doc.text(`Generated by: Stock Master`, 14, 36);

        // Financial Summary
        autoTable(doc, {
            startY: 45,
            head: [['Metric', 'Amount']],
            body: [
                ['Opening Balance', `${currency.symbol} ${dailyStats.record.opening_balance.toLocaleString()}`],
                ['(+) Sales Revenue', `${currency.symbol} ${dailyStats.salesRevenue.toLocaleString()}`],
                ['(-) Stock Purchases', `${currency.symbol} ${dailyStats.record.stock_purchases.toLocaleString()}`],
                ['(-) Other Expenses', `${currency.symbol} ${dailyStats.record.other_expenses.toLocaleString()}`],
                ['= Closing Balance', { content: `${currency.symbol} ${dailyStats.closingBalance.toLocaleString()}`, styles: { fontStyle: 'bold', fillColor: [240, 255, 240] } }],
                ['Current ROI', { content: `${dailyStats.capitalGrowth.toFixed(1)}%`, styles: { fontStyle: 'bold', textColor: dailyStats.capitalGrowth >= 0 ? [0, 128, 0] : [255, 0, 0] } }]
            ],
            theme: 'grid',
            headStyles: { fillColor: [66, 66, 66] }
        });

        // Sales Breakdown
        const daySales = sales.filter(s => s.timestamp.startsWith(selectedDate));
        if (daySales.length > 0) {
            doc.text('Sales Breakdown', 14, (doc as any).lastAutoTable.finalY + 15);

            autoTable(doc, {
                startY: (doc as any).lastAutoTable.finalY + 20,
                head: [['Time', 'Product', 'Qty', 'Total', 'Profit']],
                body: daySales.map(s => [
                    new Date(s.timestamp).toLocaleTimeString(),
                    s.productName,
                    s.quantity,
                    `${currency.symbol} ${s.totalPrice.toLocaleString()}`,
                    `${currency.symbol} ${s.profit.toLocaleString()}`
                ]),
                theme: 'striped'
            });
        }

        doc.save(`report-${selectedDate}.pdf`);
    };

    return (
        <div className="space-y-8">
            {/* Header & Date Picker */}
            <div className="flex flex-col md:flex-row justify-between items-center gap-4 bg-white p-6 rounded-3xl shadow-sm border border-slate-100">
                <div className="flex items-center gap-3">
                    <div className="bg-blue-50 p-3 rounded-xl text-blue-600">
                        <Calendar size={24} />
                    </div>
                    <div>
                        <h2 className="text-xl font-black text-slate-800">Daily Transactions</h2>
                        <p className="text-sm text-slate-500 font-medium">Tracking purchases, sales & ROI</p>
                    </div>
                </div>

                <div className="flex items-center gap-3">
                    <input
                        type="date"
                        value={selectedDate}
                        onChange={(e) => {
                            setSelectedDate(e.target.value);
                            setOpeningBalance('');
                            setStockPurchases('');
                            setOtherExpenses('');
                        }}
                        className="p-2 border border-slate-200 rounded-xl font-bold text-slate-700 focus:outline-none focus:ring-2 focus:ring-blue-500"
                    />
                    <button
                        onClick={generatePDF}
                        className="flex items-center gap-2 bg-slate-800 text-white px-4 py-2 rounded-xl font-bold hover:bg-slate-700 transition-all"
                    >
                        <Printer size={18} /> Export
                    </button>
                </div>
            </div>

            {/* Investment Overview Panel */}
            <div className="bg-white p-6 rounded-3xl shadow-sm border border-slate-100">
                <div className="flex flex-col md:flex-row items-center justify-between gap-6 mb-6">
                    <div>
                        <h3 className="text-lg font-black text-slate-800">Investment Status</h3>
                        <p className="text-sm text-slate-500">Real-time impact of today's activities on your capital</p>
                    </div>
                    <div className="text-right">
                        <p className="text-xs font-bold text-slate-400 uppercase tracking-wider">Current Shop Value</p>
                        <h2 className="text-3xl font-black text-slate-800">{currency.symbol} {dailyStats.closingBalance.toLocaleString()}</h2>
                    </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                    {/* Initial Capital Display/Input */}
                    <div className="p-4 bg-slate-50 rounded-2xl border border-slate-100">
                        <div className="flex justify-between items-start mb-2">
                            <span className="text-xs font-bold text-slate-500 uppercase">Initial Capital</span>
                            <span className="bg-blue-100 text-blue-700 text-[10px] font-bold px-2 py-1 rounded-full">Started With</span>
                        </div>
                        <div className="flex items-center gap-2">
                            <span className="text-xl font-bold text-slate-700">{currency.symbol}</span>
                            {isAdmin ? (
                                <input
                                    type="number"
                                    placeholder={initialCapital.toString()}
                                    value={capitalInput}
                                    onChange={(e) => setCapitalInput(e.target.value)}
                                    className="w-full bg-transparent text-xl font-bold text-slate-700 outline-none placeholder:text-slate-300"
                                />
                            ) : (
                                <span className="text-xl font-bold text-slate-700">{initialCapital.toLocaleString()}</span>
                            )}
                        </div>
                        {isAdmin && <p className="text-[10px] text-blue-500 mt-1 cursor-pointer" onClick={handleSave}>Click Update All to save changes</p>}
                    </div>

                    {/* Today's Impact Flow */}
                    <div className="p-4 bg-slate-50 rounded-2xl border border-slate-100 flex flex-col justify-center space-y-3">
                        <div className="flex justify-between items-center text-sm">
                            <div className="flex items-center gap-2 text-emerald-600 font-bold">
                                <ArrowUpCircle size={16} />
                                <span>Sales (In)</span>
                            </div>
                            <span className="font-bold text-emerald-600">+{currency.symbol} {dailyStats.salesImpact.toLocaleString()}</span>
                        </div>
                        <div className="w-full h-px bg-slate-200"></div>
                        <div className="flex justify-between items-center text-sm">
                            <div className="flex items-center gap-2 text-red-500 font-bold">
                                <ArrowDownCircle size={16} />
                                <span>Purchases (Out)</span>
                            </div>
                            <span className="font-bold text-red-500">-{currency.symbol} {dailyStats.purchaseImpact.toLocaleString()}</span>
                        </div>
                    </div>

                    {/* ROI Result */}
                    <div className={`p-4 rounded-2xl border flex flex-col justify-center items-center text-center ${dailyStats.capitalGrowth >= 0 ? 'bg-emerald-50 border-emerald-100 text-emerald-700' : 'bg-red-50 border-red-100 text-red-700'}`}>
                        <p className="text-xs font-bold uppercase tracking-widest mb-1">ROI / Growth</p>
                        <h3 className="text-3xl font-black">
                            {dailyStats.capitalGrowth > 0 ? '+' : ''}{dailyStats.capitalGrowth.toFixed(1)}%
                        </h3>
                        <p className="text-xs font-medium opacity-80 mt-1">
                            {dailyStats.growthAmount >= 0 ? 'Profit' : 'Loss'}: {currency.symbol} {Math.abs(dailyStats.growthAmount).toLocaleString()}
                        </p>
                    </div>
                </div>
            </div>

            {/* Daily Inputs Grid */}
            {isAdmin && (
                <div className="grid grid-cols-1 md:grid-cols-4 gap-4 bg-white p-6 rounded-3xl shadow-sm border border-slate-100">
                    <div className="md:col-span-4 mb-2 flex items-center gap-2 text-slate-800 font-bold border-b border-slate-100 pb-2">
                        <DollarSign size={18} />
                        <span>Daily Financial Inputs</span>
                        <span className="text-xs font-normal text-slate-400 ml-2">(Enter amounts for today)</span>
                    </div>

                    <div>
                        <label className="text-xs font-bold text-slate-400 uppercase">Opening Balance</label>
                        <input
                            type="number"
                            placeholder={dailyStats.record.opening_balance.toString()}
                            value={openingBalance}
                            onChange={(e) => setOpeningBalance(e.target.value)}
                            className="w-full mt-1 p-3 bg-slate-50 border border-slate-200 rounded-xl font-bold text-slate-800 focus:ring-2 focus:ring-blue-500 outline-none"
                        />
                    </div>

                    <div>
                        <label className="text-xs font-bold text-red-400 uppercase">Stock Purchases</label>
                        <input
                            type="number"
                            placeholder={dailyStats.record.stock_purchases.toString()}
                            value={stockPurchases}
                            onChange={(e) => setStockPurchases(e.target.value)}
                            className="w-full mt-1 p-3 bg-red-50 border border-red-100 rounded-xl font-bold text-red-800 focus:ring-2 focus:ring-red-500 outline-none"
                        />
                    </div>

                    <div>
                        <label className="text-xs font-bold text-slate-400 uppercase">Other Expenses</label>
                        <input
                            type="number"
                            placeholder={dailyStats.record.other_expenses.toString()}
                            value={otherExpenses}
                            onChange={(e) => setOtherExpenses(e.target.value)}
                            className="w-full mt-1 p-3 bg-slate-50 border border-slate-200 rounded-xl font-bold text-slate-800 focus:ring-2 focus:ring-blue-500 outline-none"
                        />
                    </div>

                    <div className="flex items-end">
                        <button
                            onClick={handleSave}
                            disabled={isSaving}
                            className="w-full bg-blue-600 text-white p-3 rounded-xl font-bold hover:bg-blue-700 transition-all flex items-center justify-center gap-2 active:scale-95 disabled:opacity-50 shadow-lg shadow-blue-200"
                        >
                            <Save size={18} /> {isSaving ? 'Saving...' : 'Update & Calculate'}
                        </button>
                    </div>
                </div>
            )}

            {/* Daily Expenses Breakdown Table */}
            <div className="bg-white p-6 rounded-3xl shadow-sm border border-slate-100 mt-6">
                <h3 className="text-lg font-bold text-slate-800 mb-4 flex items-center gap-2">
                    <FileText size={18} className="text-blue-600" />
                    Daily Expense Log
                </h3>
                <div className="overflow-x-auto">
                    <table className="w-full text-left text-sm">
                        <thead className="bg-slate-50 text-slate-500 font-bold uppercase text-xs">
                            <tr>
                                <th className="p-3 rounded-l-xl">Category</th>
                                <th className="p-3">Description</th>
                                <th className="p-3 text-right rounded-r-xl">Amount</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-slate-100">
                            {expenses.filter(e => e.date === selectedDate).length > 0 ? (
                                expenses.filter(e => e.date === selectedDate).map((expense, i) => (
                                    <tr key={i} className="hover:bg-slate-50 transition-colors">
                                        <td className="p-3 font-bold text-slate-700">
                                            <span className={`px-2 py-1 rounded text-[10px] bg-slate-100 text-slate-600 uppercase`}>
                                                {expense.category}
                                            </span>
                                        </td>
                                        <td className="p-3 text-slate-600">{expense.description || '-'}</td>
                                        <td className="p-3 text-right font-black text-slate-800">
                                            {currency.symbol} {expense.amount.toLocaleString()}
                                        </td>
                                    </tr>
                                ))
                            ) : (
                                <tr>
                                    <td colSpan={3} className="p-8 text-center text-slate-400 italic">
                                        No expenses recorded for this date.
                                    </td>
                                </tr>
                            )}
                        </tbody>
                    </table>
                </div>
            </div>

            {/* Existing Reports Charts */}
            <div className="mt-8">
                <h3 className="text-lg font-bold text-slate-800 mb-4 px-2">Performance Analytics</h3>
                <Reports sales={sales} products={products} currency={currency} isPremium={isPremium} />
            </div>
        </div>
    );
};

export default TransactionPage;
